import type { AchievementItem, QuestItem, ShopItem } from "./types";

export const INITIAL_QUESTS_CATALOG: readonly QuestItem[] = [
  {
    id: "quest-daily-checkin",
    title: "เช็คอินคาเฟ่หรือจุดแวะ 1 แห่ง",
    description: "ออกไปค้นพบสถานที่ใหม่ และกดปักหมุดหรือเช็คอินในหน้าแผนที่",
    category: "daily",
    rewardPoints: 50,
    rewardExp: 100,
    currentProgress: 1,
    maxProgress: 1,
    actionLabel: "เปิดแผนที่",
    actionLink: "/map?mode=places&area=Ari",
    iconKey: "map-pin",
  },
  {
    id: "quest-daily-save",
    title: "บันทึกสถานที่โปรดลงใน Saved",
    description: "เก็บร้านหรือ Trace ที่น่าสนใจลงในรายการส่วนตัวของคุณอย่างน้อย 2 แห่ง",
    category: "daily",
    rewardPoints: 30,
    rewardExp: 60,
    currentProgress: 2,
    maxProgress: 2,
    actionLabel: "ดู Saved",
    actionLink: "/saved",
    iconKey: "bookmark",
  },
  {
    id: "quest-daily-post",
    title: "แชร์เรื่องราวหรือภาพถ่าย 1 โพสต์",
    description: "แบ่งปันโมเมนต์ประทับใจ หรือกาแฟแก้วโปรดให้เพื่อนร่วมทางได้เห็น",
    category: "daily",
    rewardPoints: 40,
    rewardExp: 80,
    currentProgress: 0,
    maxProgress: 1,
    actionLabel: "เขียนโพสต์",
    actionLink: "/create?type=post",
    iconKey: "edit-3",
  },
  {
    id: "quest-explore-ari",
    title: "เดินตามรอย Trace ย่าน Ari ถึงตลาดน้อย",
    description: "เปิดดูเส้นทางแนะนำและออกเดินตามรอยเท้าของนักสร้างสรรค์",
    category: "explore",
    rewardPoints: 120,
    rewardExp: 250,
    currentProgress: 3,
    maxProgress: 6,
    actionLabel: "ดูเส้นทาง",
    actionLink: "/traces",
    iconKey: "route",
  },
  {
    id: "quest-explore-booking",
    title: "จองสิทธิ์โต๊ะหรือ Workshop ผ่าน Aevo Play",
    description: "สำรองที่นั่งร้านพาร์ทเนอร์ล่วงหน้าเพื่อรับบริการแบบเอ็กซ์คลูซีฟ",
    category: "spend",
    rewardPoints: 150,
    rewardExp: 300,
    currentProgress: 1,
    maxProgress: 1,
    actionLabel: "เลือกจองสิทธิ์",
    actionLink: "/stores/north-star-coffee/booking",
    iconKey: "zap",
  },
  {
    id: "quest-explore-review",
    title: "เขียนรีวิวสถานที่ที่ไปเยือนจริง",
    description: "บอกเล่ารสชาติและบรรยากาศที่เป็นประโยชน์ต่อนักเดินทางคนอื่น",
    category: "community",
    rewardPoints: 80,
    rewardExp: 160,
    currentProgress: 0,
    maxProgress: 1,
    actionLabel: "เขียนรีวิว",
    actionLink: "/create?type=review",
    iconKey: "coffee",
  },
];

export const INITIAL_ACHIEVEMENTS_CATALOG: readonly AchievementItem[] = [
  {
    id: "ach-founding-tastemaker",
    title: "Founding Tastemaker",
    description: "เข้าร่วมและสร้างตัวตนในยุคบุกเบิกของ Aevocado GO",
    category: "mastery",
    iconKey: "sparkles",
    rewardExp: 300,
    rewardPoints: 150,
    unlocked: true,
    unlockedAt: Date.now() - 86400000 * 5,
    currentProgress: 1,
    maxProgress: 1,
  },
  {
    id: "ach-coffee-explorer",
    title: "Specialty Coffee Hunter",
    description: "ออกสำรวจและดื่มกาแฟ Specialty ครบ 3 ร้าน",
    category: "taste",
    iconKey: "coffee",
    rewardExp: 250,
    rewardPoints: 120,
    unlocked: true,
    unlockedAt: Date.now() - 86400000 * 2,
    currentProgress: 3,
    maxProgress: 3,
  },
  {
    id: "ach-flaneur-master",
    title: "Urban Flâneur 10km",
    description: "สะสมระยะทางการเดินสำรวจเมืองทะลุ 10 กิโลเมตร",
    category: "explorer",
    iconKey: "footprints",
    rewardExp: 350,
    rewardPoints: 180,
    unlocked: false,
    currentProgress: 6.8,
    maxProgress: 10,
  },
  {
    id: "ach-creator-star",
    title: "Trailblazer Star",
    description: "สร้างสรรค์และเผยแพร่ Trace สู่สาธารณะอย่างน้อย 1 เส้นทาง",
    category: "mastery",
    iconKey: "route",
    rewardExp: 500,
    rewardPoints: 250,
    unlocked: false,
    currentProgress: 0,
    maxProgress: 1,
  },
  {
    id: "ach-patron",
    title: "Partner Patron",
    description: "จองและเช็คอินใช้งานที่ร้านค้าพาร์ทเนอร์ Aevo Play",
    category: "social",
    iconKey: "badge-check",
    rewardExp: 400,
    rewardPoints: 200,
    unlocked: true,
    unlockedAt: Date.now() - 86400000 * 1,
    currentProgress: 1,
    maxProgress: 1,
  },
];

export const SHOP_ITEMS_CATALOG: readonly ShopItem[] = [
  // 1. Avatar Decorations
  {
    id: "shop-dec-sakura",
    name: "Sakura Orbit",
    description: "กรอบกลีบดอกซากุระสีชมพูโปรยปรายรอบอวาตาร์ของคุณอย่างนุ่มนวล",
    category: "avatar_decoration",
    costPoints: 120,
    tag: "Botanical",
    accentColor: "#fbcfe8",
    decorationId: "sakura-orbit",
  },
  {
    id: "shop-dec-cyber",
    name: "Cyber Glitch Matrix",
    description: "กรอบเทคโนนีออนสีฟ้า-ชมพู พร้อมพัลส์กลิตช์เรืองแสงแห่งอนาคต",
    category: "avatar_decoration",
    costPoints: 160,
    tag: "Cyberpunk",
    accentColor: "#38bdf8",
    decorationId: "cyber-matrix",
  },
  {
    id: "shop-dec-celestial",
    name: "Celestial Stardust",
    description: "วงแหวนดวงดาวประกายเพชรในห้วงอวกาศสีม่วงครามอันน่าหลงใหล",
    category: "avatar_decoration",
    costPoints: 200,
    tag: "Cosmic",
    accentColor: "#c084fc",
    decorationId: "celestial-stardust",
  },
  {
    id: "shop-dec-mystic",
    name: "Mystic Flame Orb",
    description: "เปลวเพลิงเวทมนตร์สีครามและม่วงลาเวนเดอร์พวยพุ่งรอบอวาตาร์",
    category: "avatar_decoration",
    costPoints: 220,
    tag: "Elemental",
    accentColor: "#818cf8",
    decorationId: "mystic-flame",
  },
  {
    id: "shop-dec-emerald",
    name: "Emerald Bloom",
    description: "ช่อใบไม้ธรรมชาติสีมรกตอ่อนพลิ้วไหว สดชื่นสะบายตา",
    category: "avatar_decoration",
    costPoints: 140,
    tag: "Nature",
    accentColor: "#34d399",
    decorationId: "emerald-bloom",
  },

  // 2. Profile Effects
  {
    id: "shop-eff-sakura",
    name: "Sakura Falling Breeze",
    description: "สายลมพัดพากลีบดอกซากุระปลิวผ่านหน้าโปรไฟล์ของคุณแบบอนิเมชัน",
    category: "profile_effect",
    costPoints: 180,
    tag: "Atmospheric",
    accentColor: "#f472b6",
    effectId: "sakura-breeze",
  },
  {
    id: "shop-eff-cyber",
    name: "Cyberpunk Holo Grid",
    description: "เส้นสแกนฮอโลกราฟิกนีออนและอนุภาคข้อมูลดิจิทัลเคลื่อนที่พาดผ่านการ์ด",
    category: "profile_effect",
    costPoints: 220,
    tag: "Sci-Fi",
    accentColor: "#06b6d4",
    effectId: "cyber-scan",
  },
  {
    id: "shop-eff-cosmic",
    name: "Cosmic Galaxy Drift",
    description: "เนบิวลาดวงดาวกะพริบระยิบระยับช้าๆ มอบบรรยากาศห้วงอวกาศอันกว้างใหญ่",
    category: "profile_effect",
    costPoints: 260,
    tag: "Galaxy",
    accentColor: "#a855f7",
    effectId: "cosmic-drift",
  },
  {
    id: "shop-eff-champagne",
    name: "Champagne Starlight",
    description: "ประกายเกล็ดทองคำแชมเปญลอยขึ้นแบบละมุนตา มอบสัมผัสหรูหราพรีเมียม",
    category: "profile_effect",
    costPoints: 240,
    tag: "Luxury",
    accentColor: "#fbbf24",
    effectId: "champagne-sparkle",
  },

  // 3. Cover Banners
  {
    id: "shop-ban-tokyo",
    name: "Midnight Tokyo Banner",
    description: "ภาพปกสีน้ำเงินครามและม่วงนีออน บรรยากาศเมืองหลวงยามราตรี",
    category: "banner",
    costPoints: 100,
    tag: "Cityscape",
    accentColor: "#818cf8",
    bannerId: "midnight-tokyo",
  },
  {
    id: "shop-ban-cosmos",
    name: "Celestial Deep Cosmos",
    description: "ภาพปกห้วงอวกาศสีม่วงดำลึกลับ เสมือนมองผ่านกล้องโทรทรรศน์",
    category: "banner",
    costPoints: 120,
    tag: "Cosmic",
    accentColor: "#c084fc",
    bannerId: "celestial-cosmos",
  },
  {
    id: "shop-ban-emerald",
    name: "Emerald Rainforest",
    description: "ภาพปกโทนป่าเขียวขจีลึกซึ้ง เหมาะกับผู้หลงใหลในความร่มรื่น",
    category: "banner",
    costPoints: 100,
    tag: "Nature",
    accentColor: "#34d399",
    bannerId: "emerald-rainforest",
  },

  // 4. Partner Merchant Coupons (สามารถใช้แต้มแลกสิทธิพิเศษจากร้านจริงในระบบได้)
  {
    id: "shop-coup-north-star",
    name: "North Star Coffee: รับฟรี Specialty Drip Bag",
    description: "รับซองดริปกาแฟ Single Origin คั่วสดใหม่ 1 ซองเมื่อสั่งเครื่องดื่ม",
    category: "coupon",
    costPoints: 70,
    tag: "Free Item",
    accentColor: "#38bdf8",
    partnerStoreSlug: "north-star-coffee",
    partnerStoreName: "North Star Coffee",
    discountLabel: "Free Drip Bag",
    validDays: 30,
  },
  {
    id: "shop-coup-ceramic",
    name: "Ari Ceramic House: ส่วนลด 20% Workshop ปั้นดิน",
    description: "ส่วนลดสำหรับคอร์สทดลองปั้นและลงสีเซรามิกเบื้องต้น 2 ชั่วโมง",
    category: "coupon",
    costPoints: 120,
    tag: "Discount 20%",
    accentColor: "#f472b6",
    partnerStoreSlug: "ari-ceramic-house",
    partnerStoreName: "Ari Ceramic House",
    discountLabel: "20% OFF",
    validDays: 45,
  },
  {
    id: "shop-coup-talat-noi",
    name: "Talat Noi Roastery: ลด 50 บาท Cold Brew",
    description: "ส่วนลดพิเศษเมื่อสั่งเครื่องดื่ม Signature Cold Brew ทุกเมนู",
    category: "coupon",
    costPoints: 60,
    tag: "฿50 OFF",
    accentColor: "#fbbf24",
    partnerStoreSlug: "talat-noi-roastery",
    partnerStoreName: "Talat Noi Roastery",
    discountLabel: "฿50 OFF",
    validDays: 30,
  },
  {
    id: "shop-coup-play-perk",
    name: "Aevo Play: บัตร VIP Booking Fast-Track",
    description: "สิทธิ์จองโต๊ะหรือรอบกิจกรรมแบบ Priority ไม่ต้องรอคิวปกติ",
    category: "coupon",
    costPoints: 80,
    tag: "VIP Pass",
    accentColor: "#a855f7",
    partnerStoreSlug: "north-star-coffee",
    partnerStoreName: "Aevo Play Partners",
    discountLabel: "Fast Track",
    validDays: 60,
  },
];
